---
- name: Install Jenkins on VM1
  hosts: vm1
  become: yes
  
  tasks:
    - name: Install Java
      yum:
        name: java-11-openjdk
        state: present
        
    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins Repository
        baseurl: https://pkg.jenkins.io/redhat
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
        gpgcheck: yes
        
    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
        
    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
        
    - name: Wait for Jenkins
      wait_for:
        port: 8080
        delay: 10
        timeout: 60
        
    - name: Get admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      
    - name: Show password
      debug:
        msg: "Jenkins password: {{ jenkins_password.stdout }}"